version: '3'

services:
  mysql:
    image: 'mysql:8.0'
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: '123'
        MYSQL_PASSWORD: '123'
        MYSQL_USER: 'laravel'
        MYSQL_DATABASE: 'crud'
    volumes:
        - '.db/var/lib/mysql'
