version: '3'

services:
  mysql:
    image: 'mysql:8.0'
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: '123_test'
        MYSQL_PASSWORD: '123_test'
        MYSQL_USER: 'laravel_test'
        MYSQL_DATABASE: 'crud_test'
